# Generated by Django 5.1.6 on 2025-10-08 14:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeMetadata',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Local-Node-2', max_length=100, unique=True)),
                ('url', models.URLField(default='http://localhost:8003', help_text="Node's base URL")),
                ('api_key', models.CharField(max_length=64, unique=True)),
                ('room_count', models.IntegerField(default=0, help_text='Current number of active rooms')),
                ('load', models.FloatField(default=0.0, help_text='Current load percentage (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeerNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(help_text="Node's base URL", unique=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance')], default='offline', max_length=20)),
                ('load', models.FloatField(default=0.0, help_text='Current load percentage (0-100)')),
                ('max_rooms', models.IntegerField(default=50, help_text='Maximum rooms this node can handle')),
                ('current_rooms', models.IntegerField(default=0, help_text='Current number of active rooms')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('auto_sync_interval', models.IntegerField(default=300)),
            ],
            options={
                'db_table': 'nodes',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_node_name'), models.UniqueConstraint(fields=('url',), name='unique_node_url')],
            },
        ),
    ]
