# Generated by Django 5.1.6 on 2025-10-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeMetadata',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Local-Node-1', max_length=100, unique=True)),
                ('url', models.URLField(default='http://localhost:8002', help_text="Node's base URL")),
                ('api_key', models.CharField(max_length=64, unique=True)),
                ('room_count', models.IntegerField(default=0, help_text='Current number of active rooms')),
                ('load', models.FloatField(default=0.0, help_text='Current load percentage (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
