# Generated by Django 5.1.6 on 2025-10-07 11:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadBalanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rule_type', models.CharField(choices=[('round_robin', 'Round Robin'), ('least_connections', 'Least Connections'), ('weighted', 'Weighted'), ('random', 'Random')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, help_text='Rule-specific configuration', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'load_balance_rules',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField(help_text="Node's base URL")),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance')], default='offline', max_length=20)),
                ('load', models.FloatField(default=0.0, help_text='Current load percentage (0-100)')),
                ('max_rooms', models.IntegerField(default=50, help_text='Maximum rooms this node can handle')),
                ('current_rooms', models.IntegerField(default=0, help_text='Current number of active rooms')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_enabled', models.BooleanField(default=True)),
                ('auto_sync_interval', models.IntegerField(default=300)),
            ],
            options={
                'db_table': 'nodes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('load', models.FloatField(help_text='Node load at heartbeat time')),
                ('active_connections', models.IntegerField(help_text='Number of active WebSocket connections')),
                ('memory_usage', models.FloatField(help_text='Memory usage in MB')),
                ('cpu_usage', models.FloatField(help_text='CPU usage percentage')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='nodes.node')),
            ],
            options={
                'db_table': 'node_heartbeats',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NodeRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_name', models.CharField(max_length=100, unique=True)),
                ('node_url', models.URLField()),
                ('admin_email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_rooms_capacity', models.IntegerField(default=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'node_registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
