# Generated by Django 5.1.6 on 2025-10-01 11:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadBalanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rule_type', models.CharField(choices=[('round_robin', 'Round Robin'), ('least_connections', 'Least Connections'), ('weighted', 'Weighted'), ('random', 'Random')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, help_text='Rule-specific configuration', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'load_balance_rules',
            },
        ),
        migrations.CreateModel(
            name='NodeRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_name', models.CharField(max_length=100, unique=True)),
                ('node_url', models.URLField()),
                ('admin_email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_rooms_capacity', models.IntegerField(default=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'node_registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
